# Machine Learning Tutorial Python - 9 Decision Tree

**Decision tree algorithm** is used to **_solve classification problem in machine learning domain._** In this tutorial we will solve **employee salary prediction** problem using **decision tree.** First we will go over some theory and then do coding practice. In the end I've a very interesting exercise for you to solve.

Code: https://github.com/codebasics/py/blob/master/ML/9_decision_tree/9_decision_tree.ipynb <br>
Credit: https://www.youtube.com/watch?v=PHxYNGo8NcI&list=PLeo1K3hjS3uvCeTYTeyfe0-rN5r8zn9rw&index=10
#### Owner: Codebasics

In [1]:
import pandas as pd
df = pd.read_csv("salaries.csv")
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

#### Create input and target variables

In [2]:
inputs = df.drop("salary_more_then_100k", axis='columns')
inputs.head()

  company                  job     degree
0  google      sales executive  bachelors
1  google      sales executive    masters
2  google     business manager  bachelors
3  google     business manager    masters
4  google  computer programmer  bachelors

In [3]:
target = df['salary_more_then_100k']
target.head()

0    0
1    0
2    1
3    1
4    0
Name: salary_more_then_100k, dtype: int64

#### Create label encoder for the string variables, since ML do not recognise string. OneHotEncode is not suitable here for decision tree

In [4]:
from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

#### Fit and transformer the features (independent variable)

In [5]:
# this will automatically add the new column in the same matrix

inputs['n_company'] = le_company.fit_transform(inputs['company'])
inputs['n_job'] = le_job.fit_transform(inputs['job'])
inputs['n_degree'] = le_degree.fit_transform(inputs['degree'])

#### Get to know encoded values assigned by Label encoding

In [6]:
print(le_company.classes_) # it begins from zero
print(le_job.classes_)
print(le_degree.classes_)

['abc pharma' 'facebook' 'google']
['business manager' 'computer programmer' 'sales executive']
['bachelors' 'masters']

#### Drop all the previous columns, which are remained

In [7]:
inputs.head()

  company                  job     degree  n_company  n_job  n_degree
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

In [8]:
inputs_n = inputs.drop(['company', 'job', 'degree'], axis='columns')
inputs_n.head()

   n_company  n_job  n_degree
0          2      2         0
1          2      2         1
2          2      0         0
3          2      0         1
4          2      1         0

#### Use tree for decision

In [9]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

#### Train the decision tree

In [10]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

#### Is salary of Google, Computer Engineer, Bachelors degree > 100 k ?

In [11]:
model.predict([[2,1,0]])

array([0], dtype=int64)

#### Is salary of Google, Computer Engineer, Masters degree > 100 k ?

In [12]:
model.predict([[2,1,1]])

array([1], dtype=int64)